# Generated by Django 5.2.7 on 2025-10-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('primernombre', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PrimerNombre', max_length=1, null=True)),
                ('segundonombre', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SegundoNombre', max_length=1, null=True)),
                ('primerapellido', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PrimerApellido', max_length=1, null=True)),
                ('segundoapellido', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SegundoApellido', max_length=1, null=True)),
                ('edad', models.IntegerField(blank=True, db_column='Edad', null=True)),
                ('sexo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Sexo', max_length=1, null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
                ('cuentaid', models.IntegerField(blank=True, db_column='CuentaId', null=True)),
            ],
            options={
                'db_table': 'Administradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aosescolares',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('añoescolar', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='A�oEscolar', max_length=1, null=True)),
                ('tipoeducacionid', models.IntegerField(blank=True, db_column='TipoEducacionId', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'AñosEscolares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aosescolaresdocentes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('docenteid', models.IntegerField(blank=True, db_column='DocenteId', null=True)),
                ('añoescolarid', models.IntegerField(blank=True, db_column='A�oEscolarId', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'AñosEscolaresDocentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Barrios',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Nombre', max_length=1, null=True)),
                ('cantidadcasas', models.IntegerField(blank=True, db_column='CantidadCasas', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
                ('municipioid', models.IntegerField(blank=True, db_column='MunicipioId', null=True)),
            ],
            options={
                'db_table': 'Barrios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Casas',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('numcasa', models.IntegerField(blank=True, db_column='NumCasa', null=True)),
                ('cantidadhombres', models.IntegerField(blank=True, db_column='CantidadHombres', null=True)),
                ('cantidadmujeres', models.IntegerField(blank=True, db_column='CantidadMujeres', null=True)),
                ('totalpersonas', models.IntegerField(blank=True, db_column='TotalPersonas', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
                ('barrioid', models.IntegerField(blank=True, db_column='BarrioId', null=True)),
            ],
            options={
                'db_table': 'Casas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Centroseducativos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Nombre', max_length=1, null=True)),
                ('barrioid', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='BarrioId', max_length=1, null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
                ('directorid', models.IntegerField(blank=True, db_column='DirectorId', null=True)),
            ],
            options={
                'db_table': 'CentrosEducativos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Centroseducativosdocentes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('docenteid', models.IntegerField(blank=True, db_column='DocenteId', null=True)),
                ('centroeducativoid', models.IntegerField(blank=True, db_column='CentroEducativoId', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'CentrosEducativosDocentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contactoscentroseducativos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('contacto', models.IntegerField(blank=True, db_column='Contacto', null=True)),
                ('centroeducativoid', models.IntegerField(blank=True, db_column='CentroEducativoId', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'ContactosCentrosEducativos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contactosdirectores',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('contacto', models.IntegerField(blank=True, db_column='Contacto', null=True)),
                ('directorid', models.IntegerField(blank=True, db_column='DirectorID', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'ContactosDirectores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contactosdocentes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('contacto', models.IntegerField(blank=True, db_column='Contacto', null=True)),
                ('docenteid', models.IntegerField(blank=True, db_column='DocenteId', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'ContactosDocentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contactosinvestigadores',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('contacto', models.IntegerField(blank=True, db_column='Contacto', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
                ('investigadorid', models.IntegerField(blank=True, db_column='InvestigadorId', null=True)),
            ],
            options={
                'db_table': 'ContactosInvestigadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contactostutores',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('contacto', models.IntegerField(blank=True, db_column='Contacto', null=True)),
                ('tutorid', models.IntegerField(blank=True, db_column='TutorId', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'ContactosTutores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuentasadministradores',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Usuario', max_length=1, null=True)),
                ('contraseña', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Contrase�a', max_length=1, null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'CuentasAdministradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuentasinvestigadores',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Usuario', max_length=1, null=True)),
                ('contraseña', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Contrase�a', max_length=1, null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'CuentasInvestigadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Nombre', max_length=1, null=True)),
                ('cantidadmunicipios', models.IntegerField(blank=True, db_column='CantidadMunicipios', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'Departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('cedula', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Cedula', max_length=1, null=True)),
                ('personaid', models.IntegerField(blank=True, db_column='PersonaId', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'Directores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('personaid', models.IntegerField(blank=True, db_column='PersonaId', null=True)),
                ('cedula', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Cedula', max_length=1, null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
                ('especialidad', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Especialidad', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Docentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Docentesestudiantes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('docenteid', models.IntegerField(blank=True, db_column='DocenteId', null=True)),
                ('estudianteid', models.IntegerField(blank=True, db_column='EstudianteId', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'DocentesEstudiantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empadronados',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('personaid', models.IntegerField(blank=True, db_column='PersonaId', null=True)),
                ('relacionid', models.IntegerField(blank=True, db_column='RelacionId', null=True)),
                ('estadocivilid', models.IntegerField(blank=True, db_column='EstadoCivilId', null=True)),
                ('empleoid', models.IntegerField(blank=True, db_column='EmpleoId', null=True)),
                ('encuestainideid', models.IntegerField(blank=True, db_column='EncuestaINIDEId', null=True)),
                ('casaid', models.IntegerField(blank=True, db_column='CasaId', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'Empadronados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('empleo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Empleo', max_length=1, null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'Empleos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Encuestas',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
                ('investigadorid', models.IntegerField(blank=True, db_column='InvestigadorId', null=True)),
            ],
            options={
                'db_table': 'Encuestas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Encuestasinidetrabajadores',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
                ('casaid', models.IntegerField(blank=True, db_column='CasaId', null=True)),
                ('encuestaid', models.IntegerField(blank=True, db_column='EncuestaId', null=True)),
            ],
            options={
                'db_table': 'EncuestasINIDETrabajadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Encuestasminedescolares',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('centroeducativoid', models.IntegerField(blank=True, db_column='CentroEducativoId', null=True)),
                ('encuestaid', models.IntegerField(blank=True, db_column='EncuestaId', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'EncuestasMINEDEscolares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadosciviles',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('estadocivil', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EstadoCivil', max_length=1, null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'EstadosCiviles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('personaid', models.IntegerField(blank=True, db_column='PersonaId', null=True)),
                ('tipoeducacionid', models.IntegerField(blank=True, db_column='TipoEducacionId', null=True)),
                ('añoescolarid', models.IntegerField(blank=True, db_column='A�oEscolarId', null=True)),
                ('tutorid', models.IntegerField(blank=True, db_column='TutorId', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
                ('codigoestudiante', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CodigoEstudiante', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Estudiantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Investigadores',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('primernombre', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PrimerNombre', max_length=1, null=True)),
                ('segundonombre', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SegundoNombre', max_length=1, null=True)),
                ('primerapellido', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PrimerApellido', max_length=1, null=True)),
                ('segundoapellido', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SegundoApellido', max_length=1, null=True)),
                ('edad', models.IntegerField(blank=True, db_column='Edad', null=True)),
                ('sexo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Sexo', max_length=1, null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
                ('cuentaid', models.IntegerField(blank=True, db_column='CuentaId', null=True)),
            ],
            options={
                'db_table': 'Investigadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Nombre', max_length=1, null=True)),
                ('cantidadbarrios', models.IntegerField(blank=True, db_column='CantidadBarrios', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
                ('departamentoid', models.IntegerField(blank=True, db_column='DepartamentoId', null=True)),
            ],
            options={
                'db_table': 'Municipios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('primernombre', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PrimerNombre', max_length=1, null=True)),
                ('segundonombre', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SegundoNombre', max_length=1, null=True)),
                ('primerapellido', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PrimerApellido', max_length=1, null=True)),
                ('segundoapellido', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SegundoApellido', max_length=1, null=True)),
                ('fechadenacimiento', models.DateField(blank=True, db_column='FechaDeNacimiento', null=True)),
                ('edad', models.IntegerField(blank=True, db_column='Edad', null=True)),
                ('sexo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Sexo', max_length=1, null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'Personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Relacionesparentescos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('relacion', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Relacion', max_length=1, null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'RelacionesParentescos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposdeeducaciones',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Nombre', max_length=1, null=True)),
                ('centroeducativoid', models.IntegerField(blank=True, db_column='CentroEducativoId', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'TiposDeEducaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposdeeducacionesdocentes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('docenteid', models.IntegerField(blank=True, db_column='DocenteId', null=True)),
                ('tipoeducacionid', models.IntegerField(blank=True, db_column='TipoEducacionId', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'TiposDeEducacionesDocentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutores',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('personaid', models.IntegerField(blank=True, db_column='PersonaId', null=True)),
                ('cedula', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Cedula', max_length=1, null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'Tutores',
                'managed': False,
            },
        ),
    ]
