# Generated by Django 5.2.7 on 2025-11-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CensaData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentasinvestigadoresAdmin',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('usuario', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Usuario', max_length=30, unique=True)),
                ('password', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='password', max_length=128, null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('Role', models.CharField(choices=[('Admin', 'Administrador'), ('Inves', 'Investigador')], max_length=20)),
            ],
            options={
                'db_table': 'CuentasInvestigadores',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Cuentasinvestigadores',
        ),
    ]
