# Generated by Django 5.2.7 on 2025-10-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CensaData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Añosescolares',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('añoescolar', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='A�oEscolar', max_length=1, null=True)),
                ('tipoeducacionid', models.IntegerField(blank=True, db_column='TipoEducacionId', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'AñosEscolares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Añosescolaresdocentes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('docenteid', models.IntegerField(blank=True, db_column='DocenteId', null=True)),
                ('añoescolarid', models.IntegerField(blank=True, db_column='A�oEscolarId', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'AñosEscolaresDocentes',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Aosescolares',
        ),
        migrations.DeleteModel(
            name='Aosescolaresdocentes',
        ),
    ]
