# Generated by Django 5.2.7 on 2025-11-09 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CensaData', '0002_cuentasinvestigadoresadmin_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cuentasinvestigadoresadmin',
            table='CuentasInvestigadoresAdmin',
        ),
    ]
