# Generated by Django 5.2.7 on 2026-05-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CensaData', '0003_alter_cuentasinvestigadoresadmin_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Censos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
                ('cantidadencuestados', models.IntegerField(db_column='CantidadEncuestados')),
                ('cantidadrespuestaspositivas', models.IntegerField(db_column='CantidadRespuestasPositivas')),
                ('cantidadrespuestasnegativas', models.IntegerField(db_column='CantidadRespuestasNegativas')),
                ('cantidadencuestas', models.IntegerField(db_column='CantidadEncuestas')),
                ('muestrapoblacional', models.IntegerField(db_column='MuestraPoblacional')),
                ('poblaciontotal', models.IntegerField(db_column='PoblacionTotal')),
                ('cantidadcasasencuestadas', models.IntegerField(db_column='CantidadCasasEncuestadas')),
                ('fechainiciocenso', models.DateTimeField(db_column='FechaInicioCenso')),
                ('fechafincenso', models.DateTimeField(db_column='FechaFinCenso')),
            ],
            options={
                'db_table': 'Censos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contactosempadronados',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('contacto', models.IntegerField(db_column='Contacto')),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'ContactosEmpadronados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discapacidades',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('discapacidad', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Discapacidad', max_length=30, null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'Discapacidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discapacidadespersonas',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DiscapacidadesPersonas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Infraestructuras',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('estado', models.BooleanField(db_column='Estado')),
            ],
            options={
                'db_table': 'Infraestructuras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materialesconstrucciones',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('materialcontruccion', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MaterialContruccion', max_length=50)),
            ],
            options={
                'db_table': 'MaterialesConstrucciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Niveleseducativos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('niveleducativo', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='NivelEducativo', max_length=30)),
                ('grado', models.IntegerField(blank=True, db_column='Grado', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
            ],
            options={
                'db_table': 'NivelesEducativos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposdepisos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('tipopiso', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TipoPiso', max_length=50)),
            ],
            options={
                'db_table': 'TiposDePisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposdetechos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('tipodetecho', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TipoDeTecho', max_length=50)),
            ],
            options={
                'db_table': 'TiposDeTechos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Encuestas',
        ),
    ]
