# Generated by Django 5.2.7 on 2026-06-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CensaData', '0004_censos_contactosempadronados_discapacidades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryPassword',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('coderecovery', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CodeRecovery', max_length=255)),
                ('tokenrecovery', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TokenRecovery', max_length=255, null=True)),
                ('expires', models.DateTimeField(db_column='Expires', null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', default=True)),
            ],
            options={
                'db_table': 'RecoveryPassword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('tiporeporte', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TipoReporte', max_length=100)),
                ('espublico', models.BooleanField(blank=True, db_column='EsPublico', null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Reportes',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Cuentasadministradores',
        ),
    ]
